name: Example of caching GraalVM between jobs

on: [push]

jobs:
  with_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Cache graalvm
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/GraalVM/19.3.0-java8/x64
          key: graalvm-${{ runner.os }}-19.3.0-java8

      - name: Setup GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: 19.3.0.java8

      - name: Check binary
        run: |
          java -version
